### ISSUE TITLE
Container Access on Platform

### ISSUE THREAD

**Issue by jpthurman** [UffizziCloud/roadmap#20]
**Tell us about your request. If your feature request is related to a problem, please describe.**
I want to be able to open a shell into any of the containers in my uffizzi environment and run commands.

i.e. mount a rails console

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Select roadmap project --> in Settings for this issue**

**Comment by gadkins** [comment]
Closing this issue as it is a duplicate of https://github.com/UffizziCloud/roadmap/issues/8
